name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create SSH key file
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/ssh_private_key
          chmod 600 /tmp/ssh_private_key

      - name: Deploy code to VPS
        run: |
          ssh -o StrictHostKeyChecking=no -i /tmp/ssh_private_key nanami@160.251.234.58 << EOF
            cd /var/www/tech773.com/conoha-blog &&
            git pull origin main &&
            sudo systemctl restart apache2
          EOF
